name: wetter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image/klarer_himmel.jpg
    - assets/image/bewoelkt.jpg
    
    - assets/image/schnee.jpg
    - assets/image/gewitter.jpg
    - assets/image/nieselregen.jpg
    - assets/image/nebel.jpg
    - assets/image/standard.jpg
    